import random

prefixes = [
    "Adder",
    "Alder",
    "Amber",
    "Ant",
    "Apple",
    "Arch",
    "Ash",
    "Aspen",
    "Badger",
    "Bark",
    "Bay",
    "Bee",
    "Beech",
    "Beetle",
    "Berry",
    "Birch",
    "Bird",
    "Black",
    "Blizzard",
    "Bloom",
    "Blossom",
    "Blue",
    "Boulder",
    "Bracken",
    "Bramble",
    "Brave",
    "Breeze",
    "Briar",
    "Bright",
    "Brindle",
    "Bristle",
    "Broken",
    "Brown",
    "Bumble",
    "Buzzard",
    "Cedar",
    "Cherry",
    "Chestnut",
    "Chive",
    "Cinder",
    "Claw",
    "Cloud",
    "Clover",
    "Cone",
    "Copper",
    "Creek",
    "Crooked",
    "Crouch",
    "Crow",
    "Curl",
    "Curly",
    "Cypress",
    "Daisy",
    "Dandelion",
    "Dapple",
    "Dark",
    "Dawn",
    "Deer",
    "Dew",
    "Doe",
    "Dove",
    "Drift",
    "Drizzle",
    "Duck",
    "Dusk",
    "Dust",
    "Eagle",
    "Echo",
    "Eel",
    "Ember",
    "Fallow",
    "Fawn",
    "Feather",
    "Fennel",
    "Fern",
    "Ferret",
    "Fidget",
    "Fin",
    "Finch",
    "Fire",
    "Flail",
    "Flame",
    "Flash",
    "Flax",
    "Flicker",
    "Flint",
    "Flower",
    "Flutter",
    "Fly",
    "Fog",
    "Fox",
    "Freckle",
    "Fringe",
    "Frog",
    "Frond",
    "Frost",
    "Furze",
    "Fuzzy",
    "Golden",
    "Goose",
    "Gorse",
    "Grass",
    "Gravel",
    "Gray",
    "Gull",
    "Hail",
    "Half",
    "Hare",
    "Hawk",
    "Hay",
    "Hazel",
    "Heather",
    "Heavy",
    "Heron",
    "Hickory",
    "Holly",
    "Honey",
    "Hoot",
    "Hop",
    "Hope",
    "Hound",
    "Ice",
    "Ivy",
    "Jagged",
    "Jay",
    "Jump",
    "Juniper",
    "Kink",
    "Kestrel",
    "Kite",
    "Lake",
    "Larch",
    "Lark",
    "Leaf",
    "Leopard",
    "Lichen",
    "Light",
    "Lightning",
    "Lily",
    "Lion",
    "Little",
    "Lizard",
    "Log",
    "Long",
    "Loud",
    "Maggot",
    "Mallow",
    "Maple",
    "Marigold",
    "Marsh",
    "Meadow",
    "Midge",
    "Milk",
    "Minnow",
    "Mint",
    "Mist",
    "Mistle",
    "Misty",
    "Mole",
    "Morning",
    "Moss",
    "Moth",
    "Mottle",
    "Mouse",
    "Mud",
    "Mumble",
    "Myrtle",
    "Nectar",
    "Needle",
    "Nettle",
    "Newt",
    "Night",
    "Nut",
    "Oak",
    "Oat",
    "Odd",
    "Olive",
    "One",
    "Otter",
    "Owl",
    "Pale",
    "Parsley",
    "Patch",
    "Pear",
    "Pebble",
    "Perch",
    "Petal",
    "Pigeon",
    "Pike",
    "Pine",
    "Plum",
    "Pod",
    "Pool",
    "Poppy",
    "Pounce",
    "Prickle",
    "Primrose",
    "Puddle",
    "Quail",
    "Quick",
    "Rabbit",
    "Ragged",
    "Rain",
    "Rat",
    "Raven",
    "Red",
    "Reed",
    "Ripple",
    "River",
    "Robin",
    "Rock",
    "Rook",
    "Root",
    "Rose",
    "Rowan",
    "Rubble",
    "Running",
    "Rush",
    "Russet",
    "Rye",
    "Sage",
    "Sand",
    "Sandy",
    "Scorch",
    "Sedge",
    "Seed",
    "Shade",
    "Shadow",
    "Sharp",
    "Sheep",
    "Shell",
    "Shimmer",
    "Shining",
    "Short",
    "Shred",
    "Shrew",
    "Shy",
    "Silver",
    "Sky",
    "Slate",
    "Sleek",
    "Slight",
    "Sloe",
    "Small",
    "Smoke",
    "Snail",
    "Snake",
    "Sneeze",
    "Snip",
    "Snook",
    "Snow",
    "Soft",
    "Song",
    "Soot",
    "Sorrel",
    "Spark",
    "Sparrow",
    "Speckle",
    "Spider",
    "Spike",
    "Splash",
    "Spot",
    "Spotted",
    "Squirrel",
    "Stag",
    "Starling",
    "Stem",
    "Stoat",
    "Stone",
    "Storm",
    "Strike",
    "Stumpy",
    "Sun",
    "Sunny",
    "Swallow",
    "Sweet",
    "Swift",
    "Tall",
    "Talon",
    "Tangle",
    "Tansy",
    "Tawny",
    "Thistle",
    "Thorn",
    "Thrift",
    "Thrush",
    "Thunder",
    "Tiger",
    "Timber",
    "Toad",
    "Torn",
    "Trout",
    "Tulip",
    "Turtle",
    "Twig",
    "Vine",
    "Violet",
    "Vixen",
    "Vole",
    "Wasp",
    "Wave",
    "Weasel",
    "Web",
    "Weed",
    "Wet",
    "Wish",
    "Whisker",
    "Whistle",
    "White",
    "Whorl",
    "Wild",
    "Willow",
    "Wind",
    "Wolf",
    "Wood",
    "Wooly",
    "Wren",
    "Yarrow",
    "Yellow",
]
suffixes = [
    "bark",
    "beam",
    "bee",
    "belly",
    "berry",
    "bird",
    "blaze",
    "branch",
    "breeze",
    "briar",
    "bright",
    "brook",
    "burr",
    "bush",
    "catcher",
    "claw",
    "cloud",
    "crawl",
    "creek",
    "dapple",
    "dawn",
    "dusk",
    "dust",
    "ear",
    "eye",
    "eyes",
    "face",
    "fall",
    "fang",
    "feather",
    "fern",
    "fin",
    "fire",
    "fish",
    "flake",
    "flame",
    "flight",
    "flower",
    "foot",
    "frost",
    "fur",
    "gorse",
    "hawk",
    "haze",
    "heart",
    "jaw",
    "leaf",
    "leap",
    "leg-",
    "light",
    "mask",
    "mist",
    "moon",
    "mouse",
    "nose",
    "pad",
    "patch",
    "pelt",
    "petal",
    "pool",
    "poppy",
    "pounce",
    "puddle",
    "runner",
    "scar",
    "scratch",
    "seed",
    "shade",
    "shine",
    "sight",
    "skip",
    "sky",
    "slip",
    "snout",
    "snow",
    "song",
    "speck",
    "speckle",
    "splash",
    "spot",
    "spots",
    "spring",
    "stalk",
    "stem",
    "step",
    "stone",
    "storm",
    "stream",
    "strike",
    "stripe",
    "swoop",
    "tail",
    "talon",
    "thistle",
    "thorn",
    "throat",
    "toe",
    "tooth",
    "tuft",
    "watcher",
    "water",
    "whisker",
    "whisper",
    "willow",
    "wind",
    "wing",
    "wish",
]
coatColors = [
    "red",
    "ginger ",
    "orange",
    "silver",
    "grey",
    "light grey",
    "dark grey",
    "blue",
    "brown",
    "light brown",
    "dark brown",
    "black",
    "white",
    "cream",
    "yellow",
    "lilac",
]
eyeColors = [
    "amber",
    "hazel",
    "green",
    "blue",
    "orange",
    "copper",
    "yellow",
]
coatTypes = [
    "solid",
    "tuxedo",
    "mask and mantle",
    "cap and saddle",
    "harlequin",
    "van",
    "classic tabby",
    "mackerel tabby",
    "spotted tabby",
    "rosetted tabby",
    "patched tabby",
    "ticked tabby",
    "grizzled tabby",
    "tortoiseshell",
    "calico",
    "colorpoint",
]
genderTitles = [
    "tom",
    "she-cat",
  ]
kitGenders = [
  "she-kit",
  "tom",
  ]

def generateNameFromRole(role):
    prefix = prefixes[random.randrange(len(prefixes))]
    coatColor = coatColors[random.randrange(len(coatColors))]
    eyeColor = eyeColors[random.randrange(len(eyeColors))]
    coatType = coatTypes[random.randrange(len(coatTypes))]
    if (role == "6"):
      gender = "she-cat"
    else:
      gender = genderTitles[random.randrange(len(genderTitles))]
    if (role == "1"):
      suffix = "star"
    elif (role == "3"):
      suffix = "paw"
    elif (role == "4"):
      suffix = "kit"
      gender = kitGenders[random.randrange(len(kitGenders))]
      if (coatColor == "orange"):
        join = ", an "
      else:
        join = ", a "
      return prefix + suffix + join + coatColor + " " + gender + ","
    else:
      suffix = suffixes[random.randrange(len(suffixes))]
    return prefix + suffix + " — " + coatColor + " " + coatType + " " + gender + " with " + eyeColor + " eyes"

def generateAllegiances():
  print("LEADER: " + generateNameFromRole("1"))
  print("DEPUTY: " + generateNameFromRole("2"))
  print("MEDICINE CAT: " + generateNameFromRole("2"))
  print("WARRIORS:")
  for i in range(random.randint(1,7)):
    print(generateNameFromRole("2"))
    if (random.randint(1,100) > 65):
      print("APPRENTICE, " + generateNameFromRole("3"))
  print("QUEENS:")
  for i in range (random.randint(1,4)):
    kits = []
    for i in range (random.randint(1,4)):
      kits.append(generateNameFromRole("4"))
    kits.insert(len(kits)-1, "and")
    kits = " ".join(kits)
    print(generateNameFromRole("6") + " (mother of " + kits + ")")
  print("ELDERS:")
  for i in range(random.randint(1,3)):
    print(generateNameFromRole("2"))

def main():
  print("")
  print("what kind of name would you like?")
  print("1=leader 2=warrior 3=apprentice 4=kit 5=allegiances")
  role = input()
  if (role >= "1" and role <= "4"):
    print(generateNameFromRole(role))
  elif (role == "5"):
    generateAllegiances()
  else:
    print("invalid answer, please type a number 1-5")

while True:
  main()

